### ISSUE TITLE
not working on Windows 10

### ISSUE THREAD

**Issue by surjit** [rbtech/css-purge#12]
$ node css-purse -i plugins/Social/webroot/css/nav.css -o plugins/Social/webroot/css/na1v.css
module.js:471
    throw err;
    ^
Error: Cannot find module 'E:\webapp\css-purse'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

**Comment by AndrewEQ** [comment]
Hey surjit, I see you made a typo with the name "css-purse" instead of "css-purge".
