### ISSUE TITLE
yarn install fails on resolving dependencies

### ISSUE THREAD

**Issue by robert-skarzycki** [rbtech/css-purge#27]
Hi,

I'm working on a project that has a dependency to `grunt-css-purge` (`^1.0.2`). When I do `yarn install`, I receive following error:
```
error An unexpected error occurred: "Path must be a string. Received { integrity: 'sha1-SlKCrBZHKek2Gbz9OtFR+BfOkfU=',
  resolved: 'https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz',
  version: '1.0.1' }".
```

According to the verbose run it comes from `css-purge`, i.e.:
```
verbose 19.933 Performing "GET" request to "https://registry.yarnpkg.com/css-purge/-/css-purge-3.0.9.tgz".
verbose 20.213 TypeError: Path must be a string. Received { integrity: 'sha1-SlKCrBZHKek2Gbz9OtFR+BfOkfU=',
  resolved: 'https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz',
  version: '1.0.1' }
    at assertPath (path.js:28:11)
    at Object.isAbsolute (path.js:460:5)
    at module.exports.exports.default (C:\Program Files (x86)\Yarn\lib\cli.js:97479:16)
    at C:\Program Files (x86)\Yarn\lib\cli.js:53215:63
    at Generator.next (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:109:13
    at <anonymous>
error An unexpected error occurred: "Path must be a string. Received { integrity: 'sha1-SlKCrBZHKek2Gbz9OtFR+BfOkfU=',
  resolved: 'https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz',
  version: '1.0.1' }".
```

I've found that `package.json` in css-purge repo, there are objects like this:
```
"dependencies": {
    "amdefine": {
      "integrity": "sha1-SlKCrBZHKek2Gbz9OtFR+BfOkfU=",
      "resolved": "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz",
      "version": "1.0.1"
    },
    "ansi-regex": {
      "integrity": "sha1-w7M6te42DYbg5ijwRorn7yfWVN8=",
      "resolved": "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz",
      "version": "2.1.1"
    },
... // omitted
```
instead of string with package version. Is it valid `package.json` structure? It looks like entries from `package-lock.json`, since there is nothing about such an entries in Npm package.json docs (https://docs.npmjs.com/files/package.json).

P.S. I'm using:
```
node --version
v8.11.2

npm -v
6.1.0 

yarn --version
1.7.0

OS: Windows 10
```

**Comment by AndrewEQ** [comment]
Hey Robert, thanks for bringing this to my attention, yeah I dunno what those strange dependencies are; I ran an npm update to update the packages as one of them had a vulnerability in its dependencies, lemme remove them and test if everything still works.

**Comment by AndrewEQ** [comment]
Ok @robert-skarzycki, I've push an update to github and npm, give it a go and open another issue if the problem persists, thanks again for the heads up.
