### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by shakaran** [rbtech/css-purge#40]
I am getting this error and the JSON seems valid:

```
$ css-purge -f config3.json -v
undefined:1



[SyntaxError: Unexpected end of JSON input](url)
    at JSON.parse (<anonymous>)
    at ReadStream.<anonymous> (/usr/lib/node_modules/css-purge/lib/css-purge.js:1627:23)
    at ReadStream.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
This is config.json file (renamed to txt so github allow the upload)
[config3.txt](https://github.com/rbtech/css-purge/files/3471551/config3.txt)

**Comment by AndrewEQ** [comment]
hey @shakaran, I did a quick test and your config worked for me, could be that it couldn't read your file "public_html/css/mbr-additional-purge.css"
